#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unicodedata2
Version  : 11.0.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/b2/62/2a94b8641ea45ff4ffbec0cae13e652d31d6696cd8e20f1ae9d810044c98/unicodedata2-11.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b2/62/2a94b8641ea45ff4ffbec0cae13e652d31d6696cd8e20f1ae9d810044c98/unicodedata2-11.0.0.tar.gz
Summary  : Unicodedata backport for python 2/3 updated to the latest unicode version.
Group    : Development/Tools
License  : Apache-2.0
Requires: unicodedata2-license = %{version}-%{release}
Requires: unicodedata2-python = %{version}-%{release}
Requires: unicodedata2-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : testscenarios

%description
unicodedata2
============
unicodedata backport/updates to python 3 and python 2.

%package license
Summary: license components for the unicodedata2 package.
Group: Default

%description license
license components for the unicodedata2 package.


%package python
Summary: python components for the unicodedata2 package.
Group: Default
Requires: unicodedata2-python3 = %{version}-%{release}

%description python
python components for the unicodedata2 package.


%package python3
Summary: python3 components for the unicodedata2 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the unicodedata2 package.


%prep
%setup -q -n unicodedata2-11.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550504398
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/unicodedata2
cp LICENSE %{buildroot}/usr/share/package-licenses/unicodedata2/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/unicodedata2/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
